baseURL = "https://thinkpade15.github.io/myblog/"
languageCode = "en-us"
title = "M. Shatananda Sharma's Blog"
theme = "PaperMod"
publishDir = "public"  # ← Add this line here

[params]
  ShowReadingTime = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
