<<<<<<< HEAD
baseURL = "https://thinkpade15.github.io/myblog/"
=======
baseURL = "https://ThinkPadE15.github.io/myblog/"
>>>>>>> ec00306 (Deploy Hugo site to GitHub Pages)
languageCode = "en-us"
title = "M. Shatananda Sharma's Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
